# Generated by Django 6.0.2 on 2026-02-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo da pessoa", max_length=100
                    ),
                ),
                ("idade", models.IntegerField(help_text="Idade da pessoa")),
                (
                    "salario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Salário mensal da pessoa",
                        max_digits=8,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Endereço de email da pessoa",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        help_text="Número de telefone da pessoa (opcional)",
                        max_length=15,
                    ),
                ),
                (
                    "dtNasc",
                    models.DateField(
                        help_text="Data de nascimento da pessoa",
                        verbose_name="Data de Nascimento",
                    ),
                ),
            ],
        ),
    ]
