# Generated by Django 5.2.6 on 2025-09-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(help_text="Nome completo", max_length=100)),
                ("idade", models.IntegerField(help_text="Idade em anos")),
                (
                    "salario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Salário mensal em R$",
                        max_digits=10,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Informe um email válido", max_length=254, unique=True
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, help_text="Telefone com DDD e DDI", max_length=15
                    ),
                ),
                (
                    "dtNasc",
                    models.DateField(
                        help_text="Data de nascimento",
                        verbose_name="Data de Nascimento",
                    ),
                ),
            ],
        ),
    ]
