# Generated by Django 6.0.2 on 2026-02-23 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contatos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PessoaComAvatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "pessoa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contatos.pessoa",
                    ),
                ),
            ],
        ),
    ]
