"""
Django settings for MeuSite project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from MeuSite import utils

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-snn!%2byek035(lijcz6_@skxo1sy^f(vt6noi=z*=&_(=t$fo"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = [
    'https://localhost:8000', 
    'http://localhost:8000',
    'https://supreme-space-guacamole-5vpvp7vw5q627p6-8080.app.github.dev/',
    'http://supreme-space-guacamole-5vpvp7vw5q627p6-8080.app.github.dev/',
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'MeuApp',   # minha primeira aplicação
    'portal',
    'contatos',
    'rest_framework',
    'carros',
    'corsheaders',
    # para o Swagger
    'drf_spectacular',
    # para o JWT
    'rest_framework_simplejwt', 
    'accounts',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = "MeuSite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "MeuSite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    'DBMTCars': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'mtcars.sqlite3',
    },
}

DATABASE_ROUTERS = ['MeuSite.db_router.DBRouter']

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# --------------------------
# Swagger
# --------------------------
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),   
}

PORTA_DJANGO = utils.detectar_porta()
AMBIENTE = utils.detectar_ambiente()
PROTOCOLO = utils.detectar_protocolo()
DOMINIO = utils.detectar_dominio()
if AMBIENTE == "CODESPACE":
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https',)
    USE_X_FORWARDED_HOST = True
    CS_DOMAIN = DOMINIO
elif AMBIENTE == "LOCAL":
    # Configurações para rodar localmente
    CS_DOMAIN = f"localhost:{PORTA_DJANGO}"

SPECTACULAR_SETTINGS = {
    'TITLE': 'MeuSite API',
    'DESCRIPTION': 'API do sistema MeuSite',
    'VERSION': '1.0.0',
    # Muito útil no Codespace
    'SERVERS': [
        {
            'url': f'{PROTOCOLO}://{CS_DOMAIN}/',
            'description': 'Servidor de desenvolvimento'
        },
        {
            'url': 'http://localhost:8000/', 
            'description': 'Servidor local'
        },
    ],
}

# Configurações de email para redefinição de senha
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.seuprovedor.com'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
#EMAIL_HOST_USER = 'your-email@example.com'
#EMAIL_HOST_PASSWORD = 'your-email-password'
DEFAULT_FROM_EMAIL = 'webmaster@localhost'
#EMAIL_SUBJECT_PREFIX = '[Exemplo] '
#SERVER_EMAIL = 'server@example.com'
