# Generated by Django 5.2.8 on 2025-11-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carros", "0003_alter_mtcars_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mtcars",
            name="drat",
            field=models.FloatField(db_column="DRAT", default=0.0),
        ),
    ]
