# Generated by Django 5.2.8 on 2026-03-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contatos", "0002_pessoacomavatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pessoa",
            options={
                "managed": True,
                "verbose_name": "Pessoa com Avatar",
                "verbose_name_plural": "Pessoas com Avatar",
            },
        ),
        migrations.AddField(
            model_name="pessoa",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.DeleteModel(
            name="PessoaComAvatar",
        ),
    ]
