# Generated by Django 5.2.8 on 2025-11-17 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carros", "0002_alter_mtcars_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mtcars",
            options={"managed": True, "ordering": ["id"]},
        ),
    ]
