# Generated by Django 5.2.8 on 2025-11-17 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carros", "0004_mtcars_drat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mtcars",
            name="drat",
        ),
    ]
