# Generated by Django 6.0.2 on 2026-02-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carros", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mtcars",
            options={
                "managed": True,
                "ordering": ["id"],
                "verbose_name": "MTCars",
                "verbose_name_plural": "MTCars - MotorTrend Cars",
            },
        ),
    ]
